window.esdocSearchIndex = [
  [
    "viktor/lib/neuralnetwork/neuralnetwork.js~neuralnetwork",
    "class/lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork.html",
    "<span>NeuralNetwork</span> <span class=\"search-result-import-path\">viktor/lib/NeuralNetwork/NeuralNetwork.js</span>",
    "class"
  ],
  [
    "viktor/lib/tensor/tensor.js~tensor",
    "class/lib/Tensor/Tensor.js~Tensor.html",
    "<span>Tensor</span> <span class=\"search-result-import-path\">viktor/lib/Tensor/Tensor.js</span>",
    "class"
  ],
  [
    "viktor/lib/utils/1d/avgpoints/avgpoints.js~avgpoints",
    "function/index.html#static-function-avgPoints",
    "<span>avgPoints</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/avgPoints/avgPoints.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/0d/balancemagnitude/balancemagnitude.js~balancemagnitude",
    "function/index.html#static-function-balanceMagnitude",
    "<span>balanceMagnitude</span> <span class=\"search-result-import-path\">viktor/lib/utils/0D/balanceMagnitude/balanceMagnitude.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/balancemagnitudearray/balancemagnitudearray.js~balancemagnitudearray",
    "function/index.html#static-function-balanceMagnitudeArray",
    "<span>balanceMagnitudeArray</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/balanceMagnitudeArray/balanceMagnitudeArray.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/cummulativeavgpoints/cummulativeavgpoints.js~cummulativeavgpoints",
    "function/index.html#static-function-cummulativeAvgPoints",
    "<span>cummulativeAvgPoints</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/cummulativeAvgPoints/cummulativeAvgPoints.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/cummulativerangepoints/cummulativerangepoints.js~cummulativerangepoints",
    "function/index.html#static-function-cummulativeRangePoints",
    "<span>cummulativeRangePoints</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/cummulativeRangePoints/cummulativeRangePoints.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/evalerror/evalerror.js~evalerror",
    "function/index.html#static-function-evalError",
    "<span>evalError</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/evalError/evalError.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/evalguess/evalguess.js~evalguess",
    "function/index.html#static-function-evalGuess",
    "<span>evalGuess</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/evalGuess/evalGuess.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/gradientstep/gradientstep.js~gradientstep",
    "function/index.html#static-function-gradientStep",
    "<span>gradientStep</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/gradientStep/gradientStep.js</span>",
    "function"
  ],
  [
    "viktor/lib/ordinaryleastsquares/interceptols/interceptols.js~interceptols",
    "function/index.html#static-function-interceptOLS",
    "<span>interceptOLS</span> <span class=\"search-result-import-path\">viktor/lib/ordinaryLeastSquares/interceptOLS/interceptOLS.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/meansquarederrors/meansquarederrors.js~meansquarederrors",
    "function/index.html#static-function-meanSquaredErrors",
    "<span>meanSquaredErrors</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/meanSquaredErrors/meanSquaredErrors.js</span>",
    "function"
  ],
  [
    "viktor/lib/ordinaryleastsquares/ols_regression/ols_regression.js~ols_regression",
    "function/index.html#static-function-ols_regression",
    "<span>ols_regression</span> <span class=\"search-result-import-path\">viktor/lib/ordinaryLeastSquares/ols_regression/ols_regression.js</span>",
    "function"
  ],
  [
    "viktor/lib/curves/sigmoidcurve/sigmoidcurve.js~sigmoidcurve",
    "function/index.html#static-function-sigmoidCurve",
    "<span>sigmoidCurve</span> <span class=\"search-result-import-path\">viktor/lib/curves/sigmoidCurve/sigmoidCurve.js</span>",
    "function"
  ],
  [
    "viktor/lib/curves/sigmoidderivative/sigmoidderivative.js~sigmoidderivative",
    "function/index.html#static-function-sigmoidDerivative",
    "<span>sigmoidDerivative</span> <span class=\"search-result-import-path\">viktor/lib/curves/sigmoidDerivative/sigmoidDerivative.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/sumpoints/sumpoints.js~sumpoints",
    "function/index.html#static-function-sumPoints",
    "<span>sumPoints</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/sumPoints/sumPoints.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/sumsquarederrors/sumsquarederrors.js~sumsquarederrors",
    "function/index.html#static-function-sumSquaredErrors",
    "<span>sumSquaredErrors</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/sumSquaredErrors/sumSquaredErrors.js</span>",
    "function"
  ],
  [
    "viktor/lib/utils/1d/sumsquaredresiduals/sumsquaredresiduals.js~sumsquaredresiduals",
    "function/index.html#static-function-sumSquaredResiduals",
    "<span>sumSquaredResiduals</span> <span class=\"search-result-import-path\">viktor/lib/utils/1D/sumSquaredResiduals/sumSquaredResiduals.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.js",
    "file/lib/NeuralNetwork/NeuralNetwork.js.html",
    "lib/NeuralNetwork/NeuralNetwork.js",
    "file"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.js~neuralnetwork#constructor",
    "class/lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork.html#instance-constructor-constructor",
    "lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork#constructor",
    "method"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.js~neuralnetwork#copy",
    "class/lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork.html#instance-method-copy",
    "lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork#copy",
    "method"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.js~neuralnetwork#eval",
    "class/lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork.html#instance-method-eval",
    "lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork#eval",
    "method"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.js~neuralnetwork#train",
    "class/lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork.html#instance-method-train",
    "lib/NeuralNetwork/NeuralNetwork.js~NeuralNetwork#train",
    "method"
  ],
  [
    "lib/neuralnetwork/neuralnetwork.test.js",
    "file/lib/NeuralNetwork/NeuralNetwork.test.js.html",
    "lib/NeuralNetwork/NeuralNetwork.test.js",
    "file"
  ],
  [
    "lib/neuralnetwork/index.js",
    "file/lib/NeuralNetwork/index.js.html",
    "lib/NeuralNetwork/index.js",
    "file"
  ],
  [
    "lib/tensor/tensor.js",
    "file/lib/Tensor/Tensor.js.html",
    "lib/Tensor/Tensor.js",
    "file"
  ],
  [
    "lib/tensor/tensor.js~tensor#constructor",
    "class/lib/Tensor/Tensor.js~Tensor.html#instance-constructor-constructor",
    "lib/Tensor/Tensor.js~Tensor#constructor",
    "method"
  ],
  [
    "lib/tensor/tensor.js~tensor#numdimensions",
    "class/lib/Tensor/Tensor.js~Tensor.html#instance-method-numDimensions",
    "lib/Tensor/Tensor.js~Tensor#numDimensions",
    "method"
  ],
  [
    "lib/tensor/tensor.js~tensor#numelements",
    "class/lib/Tensor/Tensor.js~Tensor.html#instance-method-numElements",
    "lib/Tensor/Tensor.js~Tensor#numElements",
    "method"
  ],
  [
    "lib/tensor/tensor.js~tensor#shape",
    "class/lib/Tensor/Tensor.js~Tensor.html#instance-method-shape",
    "lib/Tensor/Tensor.js~Tensor#shape",
    "method"
  ],
  [
    "lib/tensor/tensor.test.js",
    "file/lib/Tensor/Tensor.test.js.html",
    "lib/Tensor/Tensor.test.js",
    "file"
  ],
  [
    "lib/tensor/index.js",
    "file/lib/Tensor/index.js.html",
    "lib/Tensor/index.js",
    "file"
  ],
  [
    "lib/curves/index.js",
    "file/lib/curves/index.js.html",
    "lib/curves/index.js",
    "file"
  ],
  [
    "lib/curves/sigmoidcurve/sigmoidcurve.js",
    "file/lib/curves/sigmoidCurve/sigmoidCurve.js.html",
    "lib/curves/sigmoidCurve/sigmoidCurve.js",
    "file"
  ],
  [
    "lib/curves/sigmoidcurve/sigmoidcurve.test.js",
    "file/lib/curves/sigmoidCurve/sigmoidCurve.test.js.html",
    "lib/curves/sigmoidCurve/sigmoidCurve.test.js",
    "file"
  ],
  [
    "lib/curves/sigmoidderivative/sigmoidderivative.js",
    "file/lib/curves/sigmoidDerivative/sigmoidDerivative.js.html",
    "lib/curves/sigmoidDerivative/sigmoidDerivative.js",
    "file"
  ],
  [
    "lib/curves/sigmoidderivative/sigmoidderivative.test.js",
    "file/lib/curves/sigmoidDerivative/sigmoidDerivative.test.js.html",
    "lib/curves/sigmoidDerivative/sigmoidDerivative.test.js",
    "file"
  ],
  [
    "lib/index.js",
    "file/lib/index.js.html",
    "lib/index.js",
    "file"
  ],
  [
    "lib/linearregression/batch_linear_regression/batch_linear_regression.js",
    "file/lib/linearRegression/batch_linear_regression/batch_linear_regression.js.html",
    "lib/linearRegression/batch_linear_regression/batch_linear_regression.js",
    "file"
  ],
  [
    "lib/linearregression/batch_linear_regression/batch_linear_regression.test.js",
    "file/lib/linearRegression/batch_linear_regression/batch_linear_regression.test.js.html",
    "lib/linearRegression/batch_linear_regression/batch_linear_regression.test.js",
    "file"
  ],
  [
    "lib/linearregression/index.js",
    "file/lib/linearRegression/index.js.html",
    "lib/linearRegression/index.js",
    "file"
  ],
  [
    "lib/ordinaryleastsquares/index.js",
    "file/lib/ordinaryLeastSquares/index.js.html",
    "lib/ordinaryLeastSquares/index.js",
    "file"
  ],
  [
    "lib/ordinaryleastsquares/interceptols/interceptols.js",
    "file/lib/ordinaryLeastSquares/interceptOLS/interceptOLS.js.html",
    "lib/ordinaryLeastSquares/interceptOLS/interceptOLS.js",
    "file"
  ],
  [
    "lib/ordinaryleastsquares/interceptols/interceptols.test.js",
    "file/lib/ordinaryLeastSquares/interceptOLS/interceptOLS.test.js.html",
    "lib/ordinaryLeastSquares/interceptOLS/interceptOLS.test.js",
    "file"
  ],
  [
    "lib/ordinaryleastsquares/ols_regression/ols_regression.js",
    "file/lib/ordinaryLeastSquares/ols_regression/ols_regression.js.html",
    "lib/ordinaryLeastSquares/ols_regression/ols_regression.js",
    "file"
  ],
  [
    "lib/ordinaryleastsquares/ols_regression/ols_regression.test.js",
    "file/lib/ordinaryLeastSquares/ols_regression/ols_regression.test.js.html",
    "lib/ordinaryLeastSquares/ols_regression/ols_regression.test.js",
    "file"
  ],
  [
    "lib/utils/0d/balancemagnitude/balancemagnitude.js",
    "file/lib/utils/0D/balanceMagnitude/balanceMagnitude.js.html",
    "lib/utils/0D/balanceMagnitude/balanceMagnitude.js",
    "file"
  ],
  [
    "lib/utils/0d/balancemagnitude/balancemagnitude.test.js",
    "file/lib/utils/0D/balanceMagnitude/balanceMagnitude.test.js.html",
    "lib/utils/0D/balanceMagnitude/balanceMagnitude.test.js",
    "file"
  ],
  [
    "lib/utils/0d/index.js",
    "file/lib/utils/0D/index.js.html",
    "lib/utils/0D/index.js",
    "file"
  ],
  [
    "lib/utils/1d/avgpoints/avgpoints.js",
    "file/lib/utils/1D/avgPoints/avgPoints.js.html",
    "lib/utils/1D/avgPoints/avgPoints.js",
    "file"
  ],
  [
    "lib/utils/1d/avgpoints/avgpoints.test.js",
    "file/lib/utils/1D/avgPoints/avgPoints.test.js.html",
    "lib/utils/1D/avgPoints/avgPoints.test.js",
    "file"
  ],
  [
    "lib/utils/1d/balancemagnitudearray/balancemagnitudearray.js",
    "file/lib/utils/1D/balanceMagnitudeArray/balanceMagnitudeArray.js.html",
    "lib/utils/1D/balanceMagnitudeArray/balanceMagnitudeArray.js",
    "file"
  ],
  [
    "lib/utils/1d/balancemagnitudearray/balancemagnitudearray.test.js",
    "file/lib/utils/1D/balanceMagnitudeArray/balanceMagnitudeArray.test.js.html",
    "lib/utils/1D/balanceMagnitudeArray/balanceMagnitudeArray.test.js",
    "file"
  ],
  [
    "lib/utils/1d/cummulativeavgpoints/cummulativeavgpoints.js",
    "file/lib/utils/1D/cummulativeAvgPoints/cummulativeAvgPoints.js.html",
    "lib/utils/1D/cummulativeAvgPoints/cummulativeAvgPoints.js",
    "file"
  ],
  [
    "lib/utils/1d/cummulativeavgpoints/cummulativeavgpoints.test.js",
    "file/lib/utils/1D/cummulativeAvgPoints/cummulativeAvgPoints.test.js.html",
    "lib/utils/1D/cummulativeAvgPoints/cummulativeAvgPoints.test.js",
    "file"
  ],
  [
    "lib/utils/1d/cummulativerangepoints/cummulativerangepoints.js",
    "file/lib/utils/1D/cummulativeRangePoints/cummulativeRangePoints.js.html",
    "lib/utils/1D/cummulativeRangePoints/cummulativeRangePoints.js",
    "file"
  ],
  [
    "lib/utils/1d/cummulativerangepoints/cummulativerangepoints.test.js",
    "file/lib/utils/1D/cummulativeRangePoints/cummulativeRangePoints.test.js.html",
    "lib/utils/1D/cummulativeRangePoints/cummulativeRangePoints.test.js",
    "file"
  ],
  [
    "lib/utils/1d/evalerror/evalerror.js",
    "file/lib/utils/1D/evalError/evalError.js.html",
    "lib/utils/1D/evalError/evalError.js",
    "file"
  ],
  [
    "lib/utils/1d/evalerror/evalerror.test.js",
    "file/lib/utils/1D/evalError/evalError.test.js.html",
    "lib/utils/1D/evalError/evalError.test.js",
    "file"
  ],
  [
    "lib/utils/1d/evalguess/evalguess.js",
    "file/lib/utils/1D/evalGuess/evalGuess.js.html",
    "lib/utils/1D/evalGuess/evalGuess.js",
    "file"
  ],
  [
    "lib/utils/1d/evalguess/evalguess.test.js",
    "file/lib/utils/1D/evalGuess/evalGuess.test.js.html",
    "lib/utils/1D/evalGuess/evalGuess.test.js",
    "file"
  ],
  [
    "lib/utils/1d/gradientstep/gradientstep.js",
    "file/lib/utils/1D/gradientStep/gradientStep.js.html",
    "lib/utils/1D/gradientStep/gradientStep.js",
    "file"
  ],
  [
    "lib/utils/1d/gradientstep/gradientstep.test.js",
    "file/lib/utils/1D/gradientStep/gradientStep.test.js.html",
    "lib/utils/1D/gradientStep/gradientStep.test.js",
    "file"
  ],
  [
    "lib/utils/1d/index.js",
    "file/lib/utils/1D/index.js.html",
    "lib/utils/1D/index.js",
    "file"
  ],
  [
    "lib/utils/1d/meansquarederrors/meansquarederrors.js",
    "file/lib/utils/1D/meanSquaredErrors/meanSquaredErrors.js.html",
    "lib/utils/1D/meanSquaredErrors/meanSquaredErrors.js",
    "file"
  ],
  [
    "lib/utils/1d/meansquarederrors/meansquarederrors.test.js",
    "file/lib/utils/1D/meanSquaredErrors/meanSquaredErrors.test.js.html",
    "lib/utils/1D/meanSquaredErrors/meanSquaredErrors.test.js",
    "file"
  ],
  [
    "lib/utils/1d/sumpoints/sumpoints.js",
    "file/lib/utils/1D/sumPoints/sumPoints.js.html",
    "lib/utils/1D/sumPoints/sumPoints.js",
    "file"
  ],
  [
    "lib/utils/1d/sumpoints/sumpoints.test.js",
    "file/lib/utils/1D/sumPoints/sumPoints.test.js.html",
    "lib/utils/1D/sumPoints/sumPoints.test.js",
    "file"
  ],
  [
    "lib/utils/1d/sumsquarederrors/sumsquarederrors.js",
    "file/lib/utils/1D/sumSquaredErrors/sumSquaredErrors.js.html",
    "lib/utils/1D/sumSquaredErrors/sumSquaredErrors.js",
    "file"
  ],
  [
    "lib/utils/1d/sumsquarederrors/sumsquarederrors.test.js",
    "file/lib/utils/1D/sumSquaredErrors/sumSquaredErrors.test.js.html",
    "lib/utils/1D/sumSquaredErrors/sumSquaredErrors.test.js",
    "file"
  ],
  [
    "lib/utils/1d/sumsquaredresiduals/sumsquaredresiduals.js",
    "file/lib/utils/1D/sumSquaredResiduals/sumSquaredResiduals.js.html",
    "lib/utils/1D/sumSquaredResiduals/sumSquaredResiduals.js",
    "file"
  ],
  [
    "lib/utils/1d/sumsquaredresiduals/sumsquaredresiduals.test.js",
    "file/lib/utils/1D/sumSquaredResiduals/sumSquaredResiduals.test.js.html",
    "lib/utils/1D/sumSquaredResiduals/sumSquaredResiduals.test.js",
    "file"
  ],
  [
    "lib/utils/index.js",
    "file/lib/utils/index.js.html",
    "lib/utils/index.js",
    "file"
  ]
]